stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: yarn install --production=false && yarn run build
    env:
      NODE_ENV: production
    envFrom:
    - sourceName: rest-api
      sourceKey: GRAPHQL_URL
    - sourceName: rest-api
      sourceKey: PORT
  - runScriptConfig:
      image: node:latest
      shellScript: yarn install --production=false && yarn run lint
- name: Release
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: yarn run semantic-release
    envFrom:
    - sourceName: rest-api
      sourceKey: GRAPHQL_URL
    - sourceName: rest-api
      sourceKey: PORT
    - sourceName: cicd
      sourceKey: GITHUB_TOKEN
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: '@demandcluster/moc-rest-api:latest'
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
