stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: yarn install --production=false && yarn run build
    env:
      NODE_ENV: production
    envFrom:
    - sourceName: rest-api
      sourceKey: GRAPHQL_URL
    - sourceName: rest-api
      sourceKey: PORT
  - runScriptConfig:
      image: node:latest
      shellScript: yarn install --production=false && yarn run lint
- name: Release
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run semantic-release
    envFrom:
    - sourceName: rest-api
      sourceKey: GRAPHQL_URL
    - sourceName: rest-api
      sourceKey: PORT
timeout: 60
notification: {}
