query blogCategoriesConnection($sort: String, $limit: Int, $start: Int, $where: JSON, $sort1: String, $limit1: Int, $start1: Int, $where1: JSON){
    blogCategoriesConnection(sort: $sort1, limit: $limit1, start: $start1, where: $where1){
        values{
            id
            created_at
            updated_at
            Title
            blog{
                id
                created_at
                updated_at
                Body
                Title
                i_18_n_locale{
                    id
                    created_at
                    updated_at
                    name
                    code
                }
                published_at
                blog_categories(sort: $sort, limit: $limit, start: $start, where: $where){
                    id
                    created_at
                    updated_at
                    Title
                    blog{
                        id
                        created_at
                        updated_at
                        Body
                        Title
                        published_at
                    }
                    i_18_n_locale{
                        id
                        created_at
                        updated_at
                        name
                        code
                    }
                    published_at
                }
            }
            i_18_n_locale{
                id
                created_at
                updated_at
                name
                code
            }
            published_at
        }
        groupBy{
            id{
                key
                connection{
                    values{
                        id
                        created_at
                        updated_at
                        Title
                        published_at
                    }
                    groupBy{
                        created_at{
                            key
                            connection{
                                aggregate{
                                    count
                                    totalCount
                                }
                            }
                        }
                        updated_at{
                            key
                        }
                        Title{
                            key
                        }
                        blog{
                            key
                        }
                        i_18_n_locale{
                            key
                        }
                        published_at{
                            key
                        }
                    }
                }
            }
        }
        aggregate{
            count
            totalCount
        }
    }
}