query blogCategories($sort: String, $limit: Int, $start: Int, $where: JSON, $sort1: String, $limit1: Int, $start1: Int, $where1: JSON, $publicationState: PublicationState){
    blogCategories(sort: $sort1, limit: $limit1, start: $start1, where: $where1, publicationState: $publicationState){
        id
        created_at
        updated_at
        Title
        blog{
            id
            created_at
            updated_at
            Body
            Title
            i_18_n_locale{
                id
                created_at
                updated_at
                name
                code
            }
            published_at
            blog_categories(sort: $sort, limit: $limit, start: $start, where: $where){
                id
                created_at
                updated_at
                Title
                blog{
                    id
                    created_at
                    updated_at
                    Body
                    Title
                    published_at
                }
                i_18_n_locale{
                    id
                    created_at
                    updated_at
                    name
                    code
                }
                published_at
            }
        }
        i_18_n_locale{
            id
            created_at
            updated_at
            name
            code
        }
        published_at
    }
}