query brandsConnection($sort: String, $limit: Int, $start: Int, $where: JSON, $sort1: String, $limit1: Int, $start1: Int, $where1: JSON){
    brandsConnection(sort: $sort1, limit: $limit1, start: $start1, where: $where1){
        values{
            id
            created_at
            updated_at
            name
            logo{
                id
                created_at
                updated_at
                name
                alternativeText
                caption
                width
                height
                formats
                hash
                ext
                mime
                size
                url
                previewUrl
                provider
                provider_metadata
                related(sort: $sort, limit: $limit, start: $start, where: $where)
            }
            description
            ranking
            published_at
        }
        groupBy{
            id{
                key
                connection{
                    values{
                        id
                        created_at
                        updated_at
                        name
                        description
                        ranking
                        published_at
                    }
                    groupBy{
                        created_at{
                            key
                            connection{
                                aggregate{
                                    count
                                    totalCount
                                    sum{
                                        ranking
                                    }
                                    avg{
                                        ranking
                                    }
                                    min{
                                        ranking
                                    }
                                    max{
                                        ranking
                                    }
                                }
                            }
                        }
                        updated_at{
                            key
                        }
                        name{
                            key
                        }
                        logo{
                            key
                        }
                        description{
                            key
                        }
                        ranking{
                            key
                        }
                        published_at{
                            key
                        }
                    }
                }
            }
        }
        aggregate{
            count
            totalCount
        }
    }
}