query CountRules($first: Int, $after: String, $last: Int, $before: String, $input: SaveJSON!){
    CountRules(input: $input){
        RuleConnect(first: $first, after: $after, last: $last, before: $before){
            edges{
                CDNimage
                _id
                active
                attributes
                categorySeparator
                channel
                channelId
                companyId
                count
                data
                description
                domain
                feedId
                groupBy
                index
                name
                percent
                userId
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                pageInfo{
                    errors
                    nodes{
                        channel
                        channelId
                        channel_market
                        country
                        errors
                        extraInfo{
                            description
                            example
                            from
                            order
                            status
                            to
                        }
                        mapping{
                            description
                            example
                            from
                            order
                            status
                            to
                        }
                        type
                    }
                    totalCount
                }
                startCursor
            }
        }
        errors
        totalCount
    }
}