query emailJobs($shopIds: [ID]!, $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int){
    emailJobs(shopIds: $shopIds, after: $after, before: $before, first: $first, last: $last, offset: $offset){
        edges{
            cursor
            node{
                _id
                updated
                status
                data{
                    to
                    subject
                }
            }
        }
        nodes{
            _id
            updated
            status
            data{
                to
                subject
            }
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            pageInfo{
                errors
                nodes{
                    channel
                    channelId
                    channel_market
                    country
                    errors
                    extraInfo{
                        description
                        example
                        from
                        order
                        status
                        to
                    }
                    mapping{
                        description
                        example
                        from
                        order
                        status
                        to
                    }
                    type
                }
                totalCount
            }
            startCursor
        }
        totalCount
    }
}