query getApiKeys($first: ConnectionLimitInt, $offset: ConnectionCursor, $shopId: String!, $title: String, $type: String){
    getApiKeys(first: $first, offset: $offset, shopId: $shopId, title: $title, type: $type){
        errors
        nodes{
            _id
            apiKey
            type
            comment
            secret
            title
        }
        totalCount
    }
}