query GetFeedProcess($channel: InputStats){
    GetFeedProcess(channel: $channel){
        count
        errors
        feedId
        inserted
        lastrun
        status
        timestamp
    }
}