query pagesConnection($sort: String, $limit: Int, $start: Int, $where: JSON){
    pagesConnection(sort: $sort, limit: $limit, start: $start, where: $where){
        values{
            id
            created_at
            updated_at
            Body
            published_at
        }
        groupBy{
            id{
                key
                connection{
                    values{
                        id
                        created_at
                        updated_at
                        Body
                        published_at
                    }
                    groupBy{
                        created_at{
                            key
                            connection{
                                aggregate{
                                    count
                                    totalCount
                                }
                            }
                        }
                        updated_at{
                            key
                        }
                        Body{
                            key
                        }
                        published_at{
                            key
                        }
                    }
                }
            }
        }
        aggregate{
            count
            totalCount
        }
    }
}