query productsByTagId($shopId: ID!, $tagId: ID!, $query: String, $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int){
    productsByTagId(shopId: $shopId, tagId: $tagId, query: $query, after: $after, before: $before, first: $first, last: $last, offset: $offset){
        edges{
            cursor
            node{
                _id
                createdAt
                position
                title
            }
        }
        nodes{
            _id
            createdAt
            position
            title
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            pageInfo{
                errors
                nodes{
                    channel
                    channelId
                    channel_market
                    country
                    errors
                    extraInfo{
                        description
                        example
                        from
                        order
                        status
                        to
                    }
                    mapping{
                        description
                        example
                        from
                        order
                        status
                        to
                    }
                    type
                }
                totalCount
            }
            startCursor
        }
        totalCount
    }
}