query roles($sort: String, $limit: Int, $start: Int, $where: JSON, $sort1: String, $limit1: Int, $start1: Int, $where1: JSON, $sort2: String, $limit2: Int, $start2: Int, $where2: JSON, $sort3: String, $limit3: Int, $start3: Int, $where3: JSON, $sort4: String, $limit4: Int, $start4: Int, $where4: JSON, $publicationState: PublicationState){
    roles(sort: $sort4, limit: $limit4, start: $start4, where: $where4, publicationState: $publicationState){
        id
        name
        description
        type
        permissions(sort: $sort2, limit: $limit2, start: $start2, where: $where2){
            id
            type
            controller
            action
            enabled
            policy
            role{
                id
                name
                description
                type
                permissions(sort: $sort, limit: $limit, start: $start, where: $where){
                    id
                    type
                    controller
                    action
                    enabled
                    policy
                }
                users(sort: $sort1, limit: $limit1, start: $start1, where: $where1){
                    id
                    created_at
                    updated_at
                    username
                    email
                    provider
                    confirmed
                    blocked
                    role{
                        id
                        name
                        description
                        type
                    }
                }
            }
        }
        users(sort: $sort3, limit: $limit3, start: $start3, where: $where3){
            id
            created_at
            updated_at
            username
            email
            provider
            confirmed
            blocked
        }
    }
}