query vendors($shopIds: [ID], $tagIds: [ID], $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int, $sortOrder: SortOrder){
    vendors(shopIds: $shopIds, tagIds: $tagIds, after: $after, before: $before, first: $first, last: $last, offset: $offset, sortOrder: $sortOrder){
        edges{
            cursor
            node{
                name
            }
        }
        nodes{
            name
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            pageInfo{
                errors
                nodes{
                    channel
                    channelId
                    channel_market
                    country
                    errors
                    extraInfo{
                        description
                        example
                        from
                        order
                        status
                        to
                    }
                    mapping{
                        description
                        example
                        from
                        order
                        status
                        to
                    }
                    type
                }
                totalCount
            }
            startCursor
        }
        totalCount
    }
}