POST https://rest.demandcluster.com/api/buckaroo/
Content-Type: "application/json"

{ "Transaction": 
    {"Key": "123",
    "Invoice": "inv123",
    "ServiceCode": "69",
    "CustomerName": "Mahmoud",
    "PayerHash": "abcabcabchash",
    "PaymentKey": "thekey",
    "Status": { "DateTime":"today" }  
    }
}