POST https://rest.demandcluster.com/api/buckaroo 

{
    "Key": "123",
    "Invoice": "inv123",
    "ServiceCode": 69,
    "CustomerName": "Mahmoud",
    "PayerHash": "abcabcabchash",
    "PaymentKey": "thekey",
    "Status": "paid"  
}